### ISSUE TITLE
service name autocompletion takes over the default sublime autocompletion

### ISSUE THREAD

**Issue by Seldaek** [pdaether/Sublime-SymfonyCommander#3]
This isn't great and it makes the plugin basically unusable for me. If I type anything in a symfony php file, all I get is a list of service ids, which is in many cases useless when I want to auto-complete a variable or function name for example.

**Comment by pdaether** [comment]
Thank you for the input!

I have optimized the autocompletion.
Now routes and service name autocompletion only takes place in Strings.
In addition if you have typed the beginning of a word, only the matching entries will be shown.

Next step will be the autocompletion of entities and template names. 
In that programming step i will try to optimized the autocompletion logic further.

**Comment by Seldaek** [comment]
Also another related thing that might be neat is autocompletion in xml for `<argument type="service" id="..." />`, and in yaml with the `@...` notation.
