### ISSUE TITLE
Autocomplete fails with dots

### ISSUE THREAD

**Issue by Seldaek** [pdaether/Sublime-SymfonyCommander#4]
The new autocompletion works way better, thanks, but if I do something like `'doctrine` it shows me all the doctrine services, but when I add the `.` then the whole autocompletion disappears. That's a bit weird.

**Comment by pdaether** [comment]
I have checked this. This is a sublime thing.
Per default the dot is a word separator so autocompletion starts again after a dot.

The word separators are defined in the settings and can be redefined in the user setings.
These are the default:

```
// Characters that are considered to separate words
    "word_separators": "./\\()\"'-:,.;<>~!@#$%^&*|+=[]{}`~?",
```

For now, you can change this setting, but of cause this will have other side effects.
I will create a workaround with the next update.

**Comment by Seldaek** [comment]
Oh ok, didn't realize this was a sublime issue. I don't know what you had planned, but it's probably not worth working doing crazy workarounds if it's a native behavior.

**Comment by pdaether** [comment]
I pushed a new version to github.
It would be great to hear your critic about the autocompletion.

If you write a word with a word separator within like `doctrine.dbal.default_connection` you still recognize that the autocompletion starts again, but SymfonyCommander tries to catch this situation now.

Additional the autocompletion now works for template and entitiy names as well (and in YAML and XML-Files).

**Comment by Seldaek** [comment]
It's much nicer like that, thanks! Template completion is cool too, but
the window is usually too narrow to show them all. I am not sure if you
have any control over the autocompletion window size as a package
author, but it'd be great to make that wider.

**Comment by pdaether** [comment]
Thank you for the feedback!
Sadly, the width of the autocompletion window can not be modified at the moment.

But you can vote for [this feature request](http://sublimetext.userecho.com/topic/85632-need-the-completion-menu-to-be-wider/).
